name: .NET Core CI

on: [push]

env:
  AZURE_WEBAPP_NAME: testdeploycsc2    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './decompressed'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      
      - uses: actions/checkout@v2

      - name: Login via Azure CLI  
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web apps
      - name: 'Decompress the package'
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq -r ./simpletestapp.zip -d "./decompressed"
        
      - name: "check the files"
        run: ls
      
      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          #publish-profile: ${{ secrets.AZURE_CREDENTIALS  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          