name: Deploy Infrastructure

on: [workflow_dispatch]

env:
  AZURE_WEBAPP_NAME: csctestappvsm    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './simpletestapp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: testdeploymentscsc
        template: ./appservicetemplate.json
    
    
    - uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./simpletestapp.zip -d ./simpletestapp

           
     
    - uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
        