name: Deploy Infrastructure

on: [worfklow_dispatch]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: testdeploymentscsc
        template: ./infrastructuredeploy.json
        